TestsApplication/TestsApplication/Controllers/TestsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Newtonsoft.Json;
using TestsApplication.Interfaces;
using TestsApplication.Models;
using System;
using System.Collections.Generic;

namespace TestsApplication.Controllers
{
    [Authorize]
    public class TestsController : Controller
    {
        private ITests<TestsModel> testsRepository;
        private IQuestions<QuestionsModel> questionsRepository;


        public TestsController(ITests<TestsModel> testsRepository, IQuestions<QuestionsModel> questionsRepository)
        {
            this.testsRepository = testsRepository;
            this.questionsRepository = questionsRepository;
        }

        public ActionResult Index()
        {
            return View(testsRepository.GetTests());
        }

        [Authorize(Roles = "Tutor,Advanced tutor")]
        public ActionResult CreateTest()
        {
            return View();
        }
       

        public ActionResult Questions()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Answers()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Answers(string id)
        {
            return View(questionsRepository.GetQuestions(id));
        }
        public ActionResult AddAnswers()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult AddAnswers(string x, string y)
        {
            var list = new List<String>();
            list.Add(y);
            ViewBag.Name = y;
            return View(list);
        }
    }
}

TestsApplication/TestsApplication/Views/Tests/AddAnswers.cshtml
@model ICollection<String>
@{
    ViewBag.Title = "AddAnswers";
}

<h2>Add Answers</h2>
@foreach (var item in Model)
{
    <h3>Question:</h3>
    <h3 id="_name">@item</h3><hr />
}
<div id="answersForm_" class="form-horizontal">

    @Html.AntiForgeryToken()

    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        <label class="col-md-2 control-label">Answer #1</label>
        <div class="col-md-4">
            <input type="text" name="name" value="" class = "form-control", id = "answerInput1" />
        </div>
            <input type="checkbox" name="name" value="" class = "col-md-1 checkbox"/>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Answer #2</label>
        <div class="col-md-4">
            <input type="text" name="name" value="" class="form-control" , id="answerInput2" />

        </div>
        <input type="checkbox" name="name" value="" class="col-md-1 checkbox" />

    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Answer #3</label>
        <div class="col-md-4">
            <input type="text" name="name" value="" class="form-control" , id="answerInput3" />

        </div>
        <input type="checkbox" name="name" value="" class="col-md-1 checkbox" />

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="saveAnswers" class="btn btn-primary" value="Save" />
            <br /><br /><label id="result" class="text-danger"></label>

        </div>
    </div>
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Custom/js")
    @Scripts.Render("~/bundles /bootstrap")
    @Scripts.Render("~/Content/css")
}

TestsApplication/TestsApplication/Views/Tests/Answers.cshtml
@model IEnumerable<TestsApplication.Models.QuestionsModel>
@{
    ViewBag.Title = "Answers";
}

<h2>Test and questions</h2>
<table class="table table-striped">
    <thead>
        <tr>
            @*<th>Id</th>*@
            <th>Test Name</th>
            <th>Questions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td hidden id="questionId_">@item.Id</td>
                <td>@item.Tests.TestName</td>
                <td><a href="http://10.10.20.45:8099/Tests/AddAnswers/@item.Tests.TestName/@item.Question" id="questionName">@item.Question</a></td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {

    @Scripts.Render("~/bundles /bootstrap")
    @Scripts.Render("~/Content/css")
}

TestsApplication/TestsApplication/Views/Tests/Create.cshtml
@model TestsApplication.Models.TestsModel
@{
    ViewBag.Title = "Create";
}


<div class="form-horizontal">
    @Html.AntiForgeryToken()
    <h4>Create New Test</h4>
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.TestName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.TestName, new { @class = "form-control", id = "testNameInput_" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Information, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Information, new { @class = "form-control", id = "infoInput_" })
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="create_Test" class="btn btn-primary" value="Create Test" />
            <br /><br /><label id="result" class="text-danger"></label>

        </div>
    </div>
    <div id="questionsForm">
        <hr />
        <h4>Questions for Test</h4>
        <div class="form-group">
            <label class="col-md-2 control-label">Question:</label>
            <div class="col-md-10">
                <input class="form-control" , id="questionInput1_" />
            </div>
        </div>

        @*<div class="form-group">
            <label class="col-md-2 control-label">Question #2</label>
            <div class="col-md-10">
                <input class="form-control" , id="questionInput2_" />
            </div>
        </div>*@

        @*<div class="form-group">
            <label class="col-md-2 control-label">Question #3</label>
            <div class="col-md-10">
                <input class="form-control" , id="questionInput3_" />
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="addQuestions" class="btn btn-primary" value="Add Questions" />
            </div>
            <br /><label id="result" class="text-danger"></label>
        </div>
    </div>
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Custom/js")
    @Scripts.Render("~/bundles /bootstrap")
    @Scripts.Render("~/Content/css")
}

TestsApplication/TestsApplication/Views/Tests/CreateTest.cshtml
@model TestsApplication.Models.TestsModel
@{
    ViewBag.Title = "CreateTest";
}

<h2>Create Test</h2>


<div class="form-horizontal">
    @Html.AntiForgeryToken()
    <h4>New Test.</h4>
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.TestName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.TestName, new { @class = "form-control", id = "testNameInput" })
            <br /><label id="result" class="text-danger"></label>

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Information, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Information, new { @class = "form-control",  id = "infoInput" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="createTest" class="btn btn-primary" value="Create Test" />
        </div>
    </div>
    @using (Html.BeginForm("Questions", "Tests"))
    {
        <button type="submit" class="btn btn-primary">Questions</button>
    }

</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Custom/js")
    @Scripts.Render("~/bundles /bootstrap")    
    @Scripts.Render("~/Content/css")
}


TestsApplication/TestsApplication/Views/Tests/Index.cshtml
@model IEnumerable<TestsApplication.Models.TestsModel>
@{
    ViewBag.Title = "Index";
}

<h2>List of available Tests</h2>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Test Name</th>
            <th>Information</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var test in Model)
        {
        <tr>
            <td hidden id="testId_">@test.Id</td>
            <td>@test.TestName</td>
            <td>@test.Information</td>
            <td>
                @using (Html.BeginForm("Index", "Tests"))
                {
                    <button type="submit" class="btn btn-primary">Start Test</button>
                }

            </td>
        </tr>
        }
        </tbody>
    </table>

<hr/>


@*@using (Html.BeginForm("CreateTest", "Tests"))
{
    <button type="submit" class="btn btn-primary">Create New Test2</button>
}*@

@using (Html.BeginForm("Create", "Tests"))
{
    <button type="submit" class="btn btn-primary">Create New Test</button>
}
@section Scripts {

    @Scripts.Render("~/bundles /bootstrap")
    @Scripts.Render("~/Content/css")
}


TestsApplication/TestsApplication/Views/Tests/Questions.cshtml
@model TestsApplication.Models.QuestionsModel

@{
    ViewBag.Title = "Questions";
}

<h2>Questions</h2>
@Html.AntiForgeryToken()

<form id ="questionsForm_" class="form-horizontal">
    @Html.AntiForgeryToken()

    @Html.ValidationSummary("", new {@class = "text-danger"})

    <div class="form-group">
        <label class="col-md-2 control-label">Question #1</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Question, new {@class = "form-control", id = "questionInput1"})
            <label id="result" class="text-danger"></label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Question #2</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Question, new {@class = "form-control", id = "questionInput2"})
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Question #3</label>
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Question, new {@class = "form-control", id = "questionInput3"})
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="saveQuestions" class="btn btn-primary" value="Save"/>
        </div>
    </div>
</form>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Custom/js")
    @Scripts.Render("~/bundles /bootstrap")
    @Scripts.Render("~/Content/css")
}




